source = ~/.config/hypr/system/programs.conf
source = ~/.config/hypr/system/autostart.conf
source = ~/.config/hypr/system/env.conf
source = ~/.config/hypr/system/general.conf
source = ~/.config/hypr/ui/decoration.conf
source = ~/.config/hypr/animations/dynamic.conf
source = ~/.config/hypr/system/monitors.conf

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

master {
    new_status = master
}

source = ~/.config/hypr/input/input.conf
source = ~/.config/hypr/input/gestures.conf
source = ~/.config/hypr/input/keybinds.conf
source = ~/.config/hypr/system/windowrules.conf

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
